/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateactionapp;

/**
 *
 * @author aaron
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class ClimateEducationHub extends javax.swing.JFrame {

    /**
     * Creates new form ClimateEducationHub
     */
    public ClimateEducationHub() {
        initComponents();
         desertlbl.setVisible(false);
        icelbl.setVisible(false);
        landlbl.setVisible(false);
      
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void writeQuizScoreToFile(int score) {
    try (BufferedReader reader = new BufferedReader(new FileReader("quiz_score.txt"))) {
        // Read existing scores to determine the next sequence number
        int sequenceNumber = 1;
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.startsWith("Quiz Score ")) {
                sequenceNumber++;
            }
        }

        // Append the new score with the sequence number
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("quiz_score.txt", true))) {
            writer.write("Quiz Score " + sequenceNumber + ": " + score);
            writer.newLine();  // Add a new line for better readability
            System.out.println("Quiz score written to file successfully.");
        }
    } catch (IOException e) {
        System.err.println("Error writing quiz score to file: " + e.getMessage());
    }
}
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        HubPanel = new javax.swing.JPanel();
        Titlelbl = new javax.swing.JLabel();
        quizlbl = new javax.swing.JLabel();
        q1lbl = new javax.swing.JLabel();
        q2lbl = new javax.swing.JLabel();
        q3lbl = new javax.swing.JLabel();
        q4lbl = new javax.swing.JLabel();
        q5lbl = new javax.swing.JLabel();
        trueradio1 = new javax.swing.JRadioButton();
        falseradio2 = new javax.swing.JRadioButton();
        trueradio3 = new javax.swing.JRadioButton();
        falseradio4 = new javax.swing.JRadioButton();
        trueradio5 = new javax.swing.JRadioButton();
        falseradio6 = new javax.swing.JRadioButton();
        trueradio7 = new javax.swing.JRadioButton();
        falseradio8 = new javax.swing.JRadioButton();
        trueradio9 = new javax.swing.JRadioButton();
        falseradio10 = new javax.swing.JRadioButton();
        comment2 = new javax.swing.JLabel();
        quizbtn = new javax.swing.JButton();
        desertbtn = new javax.swing.JButton();
        desertlbl = new javax.swing.JLabel();
        icebtn = new javax.swing.JButton();
        landbtn = new javax.swing.JButton();
        icelbl = new javax.swing.JLabel();
        landlbl = new javax.swing.JLabel();
        imagelbl = new javax.swing.JLabel();
        Homebtn = new javax.swing.JButton();
        Nextbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HubPanel.setBackground(new java.awt.Color(0, 204, 204));

        Titlelbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Titlelbl.setText("Climate Education Hub");

        quizlbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        quizlbl.setText("Climate Quiz");

        q1lbl.setText("Q1) Carbon dioxide (Co2) is the primary greenhouse gas responsible for climate change.");

        q2lbl.setText("Q2) Deforistation contributes to climate change by releasing stored carbon dioxide.");

        q3lbl.setText("Q3) Solar power is a renewable energy resource.");

        q4lbl.setText("Q4) Melting glaciers and ice caps are the main contributers to sea level rise.");

        q5lbl.setText("Q5) The \"greenhouse effect\" contributes to global warming by trapping heat in the Earth's atmosphere");

        trueradio1.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(trueradio1);
        trueradio1.setText("True");
        trueradio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueradio1ActionPerformed(evt);
            }
        });

        falseradio2.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup1.add(falseradio2);
        falseradio2.setText("False");

        trueradio3.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup2.add(trueradio3);
        trueradio3.setText("True");
        trueradio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueradio3ActionPerformed(evt);
            }
        });

        falseradio4.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup2.add(falseradio4);
        falseradio4.setText("False");
        falseradio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseradio4ActionPerformed(evt);
            }
        });

        trueradio5.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup3.add(trueradio5);
        trueradio5.setText("True");

        falseradio6.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup3.add(falseradio6);
        falseradio6.setText("False");

        trueradio7.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup4.add(trueradio7);
        trueradio7.setText("True");

        falseradio8.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup4.add(falseradio8);
        falseradio8.setText("False");
        falseradio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseradio8ActionPerformed(evt);
            }
        });

        trueradio9.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup5.add(trueradio9);
        trueradio9.setText("True");

        falseradio10.setBackground(new java.awt.Color(0, 204, 204));
        buttonGroup5.add(falseradio10);
        falseradio10.setText("False");

        comment2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comment2.setText("Your score is /5");

        quizbtn.setText("Submit quiz");
        quizbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizbtnActionPerformed(evt);
            }
        });

        desertbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/climateactionapp/desert.jpg"))); // NOI18N
        desertbtn.setText("jButton1");
        desertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desertbtnActionPerformed(evt);
            }
        });

        desertlbl.setText("Deserts characterized by low vegetation cover and arid conditions, impact climate change by contributing the albedo effect.");

        icebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/climateactionapp/iceberg.jpg"))); // NOI18N
        icebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icebtnActionPerformed(evt);
            }
        });

        landbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/climateactionapp/land.jpg"))); // NOI18N
        landbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landbtnActionPerformed(evt);
            }
        });

        icelbl.setText("Climate change excelerates the melting of ice and permafrost, releasing stored greenhouse gases like methane and carbon dioxide.");

        landlbl.setText("Natural greenland areas, such as forests and grasslands, act as crucial carbon sinks absorbing carbon dioxide through phototsynthesis.");

        imagelbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imagelbl.setText("Click image's to display information");

        Homebtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Homebtn.setText("Home");
        Homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebtnActionPerformed(evt);
            }
        });

        Nextbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nextbtn.setText("Next page");
        Nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HubPanelLayout = new javax.swing.GroupLayout(HubPanel);
        HubPanel.setLayout(HubPanelLayout);
        HubPanelLayout.setHorizontalGroup(
            HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HubPanelLayout.createSequentialGroup()
                .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HubPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4lbl)
                            .addComponent(q2lbl)
                            .addComponent(falseradio2)
                            .addComponent(trueradio7)
                            .addComponent(falseradio8)
                            .addComponent(q5lbl)
                            .addComponent(trueradio9)
                            .addComponent(falseradio10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trueradio1)
                            .addComponent(q1lbl)
                            .addComponent(q3lbl)
                            .addComponent(trueradio3)
                            .addComponent(falseradio4)
                            .addComponent(trueradio5)
                            .addComponent(falseradio6)
                            .addGroup(HubPanelLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(quizlbl))
                            .addComponent(Homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HubPanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(Titlelbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HubPanelLayout.createSequentialGroup()
                        .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(desertlbl)
                                .addComponent(icelbl)
                                .addComponent(landlbl))
                            .addGroup(HubPanelLayout.createSequentialGroup()
                                .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HubPanelLayout.createSequentialGroup()
                                        .addComponent(desertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(icebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(HubPanelLayout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(imagelbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(HubPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
            .addGroup(HubPanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comment2)
                    .addComponent(quizbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HubPanelLayout.setVerticalGroup(
            HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HubPanelLayout.createSequentialGroup()
                .addComponent(Titlelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HubPanelLayout.createSequentialGroup()
                        .addComponent(desertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HubPanelLayout.createSequentialGroup()
                        .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(landbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(landlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desertlbl)
                .addGap(50, 50, 50)
                .addComponent(quizlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueradio1)
                .addGap(0, 0, 0)
                .addComponent(falseradio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueradio3)
                .addGap(0, 0, 0)
                .addComponent(falseradio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q3lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueradio5)
                .addGap(0, 0, 0)
                .addComponent(falseradio6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueradio7)
                .addGap(0, 0, 0)
                .addComponent(falseradio8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueradio9)
                .addGap(0, 0, 0)
                .addComponent(falseradio10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(quizbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comment2)
                .addGap(88, 88, 88)
                .addGroup(HubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        desertlbl.getAccessibleContext().setAccessibleName("desert");
        desertlbl.getAccessibleContext().setAccessibleDescription("");

        jScrollPane1.setViewportView(HubPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Event handler for the "Next Page" button.
     * Opens the next page (ClimateEducationHub2) when the button is clicked.
     */
    private void NextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextbtnActionPerformed
        // TODO add your handling code here:
        ClimateEducationHub2 hub2 = new ClimateEducationHub2 ();
        hub2.setVisible(true);
    }//GEN-LAST:event_NextbtnActionPerformed
     
    /**
     * Event handler for the "Home" button.
     * Opens the home page (ClimateHome) when the button is clicked.
     */
    private void HomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebtnActionPerformed
        // TODO add your handling code here:
        ClimateHome homegui = new ClimateHome();
        homegui.setVisible(true);
    }//GEN-LAST:event_HomebtnActionPerformed

    /**
     * Event handler for the "Land" button.
     * Sets visibility for content labels to display information about land.
     */
    private void landbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landbtnActionPerformed
        // TODO add your handling code here:
        desertlbl.setVisible(false);
        icelbl.setVisible(false);
        landlbl.setVisible(true);
    }//GEN-LAST:event_landbtnActionPerformed

     /**
     * Event handler for the "Ice" button.
     * Sets visibility for content labels to display information about ice.
     */
    private void icebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icebtnActionPerformed
        desertlbl.setVisible(false);
        icelbl.setVisible(true);
        landlbl.setVisible(false);
    }//GEN-LAST:event_icebtnActionPerformed

    
    /**
     * Event handler for the "Desert" button.
     * Sets visibility for content labels to display information about deserts.
     */
    private void desertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desertbtnActionPerformed
        // TODO add your handling code here:
        desertlbl.setVisible(true);
        icelbl.setVisible(false);
        landlbl.setVisible(false);
    }//GEN-LAST:event_desertbtnActionPerformed

      /**
     * Event handler for the "Submit Quiz" button.
     * Calls the calculateQuizScore method to calculate the quiz score.
     */
    private void quizbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizbtnActionPerformed
        // TODO add your handling code here:
        calculateQuizScore();
    }//GEN-LAST:event_quizbtnActionPerformed

    private void falseradio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseradio8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_falseradio8ActionPerformed

    private void falseradio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseradio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_falseradio4ActionPerformed

    private void trueradio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueradio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueradio3ActionPerformed

    private void trueradio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueradio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueradio1ActionPerformed



  private void calculateQuizScore() {
    int score = 0;

    // Check answers for each question
    if (trueradio1.isSelected()) {
        // User selected "True" for Q1
        score++;
    }

    if (falseradio4.isSelected()) {
        // User selected "False" for Q2
        score++;
    }

    if (trueradio5.isSelected()) {
        // User selected "True" for Q3
        score++;
    }

    if (falseradio8.isSelected()) {
        // User selected "False" for Q4
        score++;
    }

    if (trueradio9.isSelected()) {
        // User selected "True" for Q5
        score++;
    }

    displayQuizResult(score);
}

  /**
     * Displays the quiz result in the comment2 label.
     * @param score The quiz score to be displayed.
     */
    private void displayQuizResult(int score) {
        comment2.setText("Your score is: " + score + "/5");
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new ClimateEducationHub().setVisible(true);
        });
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Homebtn;
    private javax.swing.JPanel HubPanel;
    private javax.swing.JButton Nextbtn;
    private javax.swing.JLabel Titlelbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel comment2;
    private javax.swing.JButton desertbtn;
    private javax.swing.JLabel desertlbl;
    private javax.swing.JRadioButton falseradio10;
    private javax.swing.JRadioButton falseradio2;
    private javax.swing.JRadioButton falseradio4;
    private javax.swing.JRadioButton falseradio6;
    private javax.swing.JRadioButton falseradio8;
    private javax.swing.JButton icebtn;
    private javax.swing.JLabel icelbl;
    private javax.swing.JLabel imagelbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton landbtn;
    private javax.swing.JLabel landlbl;
    private javax.swing.JLabel q1lbl;
    private javax.swing.JLabel q2lbl;
    private javax.swing.JLabel q3lbl;
    private javax.swing.JLabel q4lbl;
    private javax.swing.JLabel q5lbl;
    private javax.swing.JButton quizbtn;
    private javax.swing.JLabel quizlbl;
    private javax.swing.JRadioButton trueradio1;
    private javax.swing.JRadioButton trueradio3;
    private javax.swing.JRadioButton trueradio5;
    private javax.swing.JRadioButton trueradio7;
    private javax.swing.JRadioButton trueradio9;
    // End of variables declaration//GEN-END:variables
}
