/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateactionapp;

/**
 *
 * @author aaron
 */
public class ClimateHome extends javax.swing.JFrame {

    /**
     * Creates new form ClimateHome
     */
    public ClimateHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cftbtn = new javax.swing.JButton();
        cehbtn = new javax.swing.JButton();
        ecobtn = new javax.swing.JButton();
        titlelbl = new javax.swing.JLabel();
        imglbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        cftbtn.setBackground(new java.awt.Color(0, 255, 51));
        cftbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cftbtn.setText("Carbon Footprint Tracker");
        cftbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cftbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cftbtnActionPerformed(evt);
            }
        });

        cehbtn.setBackground(new java.awt.Color(0, 204, 204));
        cehbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cehbtn.setText("Climate Education Hub");
        cehbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cehbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cehbtnActionPerformed(evt);
            }
        });

        ecobtn.setBackground(new java.awt.Color(255, 255, 0));
        ecobtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ecobtn.setText("Energy Consumption Optimization");
        ecobtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ecobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecobtnActionPerformed(evt);
            }
        });

        titlelbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        titlelbl.setText("Climate Action Homepage");

        imglbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/climateactionapp/homebackground.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cftbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cehbtn)
                    .addComponent(ecobtn)
                    .addComponent(titlelbl)
                    .addComponent(imglbl))
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(cftbtn)
                .addGap(18, 18, 18)
                .addComponent(cehbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ecobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(imglbl))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cehbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cehbtnActionPerformed
        // TODO add your handling code here:
        ClimateEducationHub climateeducationhub = new ClimateEducationHub();
        climateeducationhub.setVisible(true);
    }//GEN-LAST:event_cehbtnActionPerformed

    private void cftbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cftbtnActionPerformed
        // TODO add your handling code here:
                CarbCalcGUI cft = new CarbCalcGUI();
        cft.setVisible(true);
    }//GEN-LAST:event_cftbtnActionPerformed

    private void ecobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecobtnActionPerformed
        // TODO add your handling code here:
                EnergyConsumptionOptimization climateeducationhub = new ClimateEducationHub();
        climateeducationhub.setVisible(true);
    }//GEN-LAST:event_ecobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClimateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClimateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClimateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClimateHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClimateHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cehbtn;
    private javax.swing.JButton cftbtn;
    private javax.swing.JButton ecobtn;
    private javax.swing.JLabel imglbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
