/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateactionapp;

import javax.swing.JOptionPane;

/**
 *
 * @author aaron
 */
public class ClimateEducationHub2 extends javax.swing.JFrame {

    /**
     * Creates new form ClimateEducationHub2
     */
    public ClimateEducationHub2() {
        initComponents();
        displayEnvironmentalTips(); // Populate tips in the constructor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HubPane2 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        homebtn2 = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        Tiplbl2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tiptxtarea = new javax.swing.JTextArea();
        Displaybtn = new javax.swing.JButton();
        HideTipsbtn = new javax.swing.JButton();
        AddTipBtn = new javax.swing.JButton();
        SearchTipbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HubPane2.setBackground(new java.awt.Color(0, 204, 204));

        titlelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titlelbl.setText("Climate Education Hub");

        homebtn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homebtn2.setText("Home");
        homebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtn2ActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        Tiplbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tiplbl2.setText("Environmental Tips");

        Tiptxtarea.setColumns(20);
        Tiptxtarea.setRows(5);
        jScrollPane2.setViewportView(Tiptxtarea);

        Displaybtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Displaybtn.setText("Display ");
        Displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybtnActionPerformed(evt);
            }
        });

        HideTipsbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HideTipsbtn.setText("Delete");
        HideTipsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideTipsbtnActionPerformed(evt);
            }
        });

        AddTipBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddTipBtn.setText("Add");
        AddTipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTipBtnActionPerformed(evt);
            }
        });

        SearchTipbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchTipbtn.setText("Search");
        SearchTipbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTipbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HubPane2Layout = new javax.swing.GroupLayout(HubPane2);
        HubPane2.setLayout(HubPane2Layout);
        HubPane2Layout.setHorizontalGroup(
            HubPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HubPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titlelbl)
                .addGap(169, 169, 169))
            .addGroup(HubPane2Layout.createSequentialGroup()
                .addGroup(HubPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HubPane2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(Tiplbl2))
                    .addGroup(HubPane2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(HubPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HubPane2Layout.createSequentialGroup()
                                .addComponent(homebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HubPane2Layout.createSequentialGroup()
                                .addComponent(AddTipBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Displaybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(SearchTipbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HideTipsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        HubPane2Layout.setVerticalGroup(
            HubPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HubPane2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titlelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tiplbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HubPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HideTipsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Displaybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTipBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTipbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(HubPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(HubPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtn2ActionPerformed
        // TODO add your handling code here:
        ClimateHome homegui = new ClimateHome();
        homegui.setVisible(true);
    }//GEN-LAST:event_homebtn2ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         ClimateEducationHub climateeducationhub = new ClimateEducationHub();
        climateeducationhub.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void DisplaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybtnActionPerformed
        // TODO add your handling code here:
         tipsVisible = !tipsVisible; // Toggle the visibility state
         displayEnvironmentalTips();
    }//GEN-LAST:event_DisplaybtnActionPerformed

    private void HideTipsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideTipsbtnActionPerformed
        // TODO add your handling code here:
        tipsVisible = false;
        displayEnvironmentalTips();
    }//GEN-LAST:event_HideTipsbtnActionPerformed

    private void SearchTipbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTipbtnActionPerformed
        // TODO add your handling code here:
        // Prompt the user for a keyword to search for tips
        String keyword = JOptionPane.showInputDialog(this, "Enter a keyword to search for tips:");
        searchEnvironmentalTips(keyword);
    }//GEN-LAST:event_SearchTipbtnActionPerformed

    private void AddTipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTipBtnActionPerformed
        // TODO add your handling code here:
        // Prompt the user for a new tip
        String newTip = JOptionPane.showInputDialog(this, "Enter a new environmental tip:");
        addEnvironmentalTip(newTip);
        displayEnvironmentalTips(); // Refresh the displayed tips
    }//GEN-LAST:event_AddTipBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClimateEducationHub2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClimateEducationHub2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClimateEducationHub2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClimateEducationHub2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClimateEducationHub2().setVisible(true);
            }
        });
    }
    
    private boolean tipsVisible = true; // Variable to track whether tips are currently visible
    
    // Array to store environmental tips
    private String[] environmentalTips = {
        "Turn off lights, electronic devices, and taps when not in use.",
        "Use reusable bags, water bottles, and containers instead of single-use products.",
        "Reduce car usage and walk when you have the chance.",
        "Plant trees and preserve green spaces.",
        "Recycle and compost as much as possible."
    };


    private void displayEnvironmentalTips() {
   Tiplbl2.setText("Environmental Tips:");
   
    if (tipsVisible) {
        Tiptxtarea.setText("");  

        // Populate tipsTextArea with environmental tips
        for (String tip : environmentalTips) {
            Tiptxtarea.append("- " + tip + "\n");
        }
    } else {
        Tiptxtarea.setText(""); // Clear the text area if tips are not visible
    }
}

     // Method to add a new environmental tip to the array
    private void addEnvironmentalTip(String newTip) {
        // Check if the new tip is not empty
        if (!newTip.trim().isEmpty()) {
            // Add the new tip to the array
            String[] newTipsArray = new String[environmentalTips.length + 1];
            System.arraycopy(environmentalTips, 0, newTipsArray, 0, environmentalTips.length);
            newTipsArray[newTipsArray.length - 1] = newTip;
            environmentalTips = newTipsArray;

            // Display a message to inform the user
            JOptionPane.showMessageDialog(this, "New environmental tip added successfully!");
        } else {
            // Display an error message if the new tip is empty
            JOptionPane.showMessageDialog(this, "Please enter a valid environmental tip!");
        }
    }

    // Method to search for environmental tips containing a specific keyword
    private void searchEnvironmentalTips(String keyword) {
        // Check if the keyword is not empty
        if (!keyword.trim().isEmpty()) {
            // Search for tips containing the keyword
            StringBuilder searchResults = new StringBuilder();
            for (String tip : environmentalTips) {
                if (tip.toLowerCase().contains(keyword.toLowerCase())) {
                    searchResults.append("- ").append(tip).append("\n");
                }
            }

            // Display the search results in the text area
            if (searchResults.length() > 0) {
                Tiptxtarea.setText("Search Results for '" + keyword + "':\n" + searchResults.toString());
            } else {
                Tiptxtarea.setText("No tips found for '" + keyword + "'.");
            }
        } else {
            // Display an error message if the keyword is empty
            JOptionPane.showMessageDialog(this, "Please enter a keyword for the search!");
        }
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTipBtn;
    private javax.swing.JButton Displaybtn;
    private javax.swing.JButton HideTipsbtn;
    private javax.swing.JPanel HubPane2;
    private javax.swing.JButton SearchTipbtn;
    private javax.swing.JLabel Tiplbl2;
    private javax.swing.JTextArea Tiptxtarea;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton homebtn2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
